function(cpptools_export_binary_root_props)
  # cpptools 在 binary tree 中的逻辑根
  set(_root "${CMAKE_BINARY_DIR}/cpptools")

  set(_out "${_root}/msvs/generated/cpptools_binary_root.props")
  file(MAKE_DIRECTORY "${_root}/msvs/generated")

  file(WRITE "${_out}"
"<?xml version=\"1.0\" encoding=\"utf-8\"?>
<Project xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
  <PropertyGroup>
    <!-- Binary root of cpptools (generated by CMake) -->
    <CPPTTOOLS_BINARY_ROOT>${_root}</CPPTTOOLS_BINARY_ROOT>
  </PropertyGroup>
</Project>
")

  message(STATUS \"[cpptools] Exported cpptools_binary_root.props: ${_out}\")
endfunction()
